### ISSUE TITLE
Issue building

### ISSUE THREAD

**Issue by carlosgjr** [akorchev/radzen#37]
Getting the following error below. Connection info attached.
![radzen connection](https://cloud.githubusercontent.com/assets/7093207/25832838/c4b9d0d4-3432-11e7-96b4-5a72e87683bb.png)ERROR in C:/Users/cgonz/Documents/Visual Studio 2015/Projects/RADZEN/client/src/app/azure-mdb.service.ts (14,26): Property 'azureMdb' does not exist on type '{ azureMetadata: string; production: boolean; }'.

ERROR in C:/Users/cgonz/Documents/Visual Studio 2015/Projects/RADZEN/client/src/app/azure-metadata-manager.service.ts (15,26): Property 'azureMetadataManager' does not exist on type '{ azureMetadata: string; production: boolean; }'.

ng-cli: webpack: Failed to compile.

**Comment by enchev** [comment]
Hey @carlosgjr,

Can you send us your Radzen app `meta` folder to test your scenario locally?

**Comment by carlosgjr** [comment]
I was able to build solution by creating a new project in a new subdirectory but there are issues.  Several screens are blank.  Attached is the meta folder
[meta.zip](https://github.com/akorchev/radzen/files/986517/meta.zip)

**Comment by enchev** [comment]
We were able to reproduce the problem and we are working on fix for this. I'll write here when the fix is ready.

**Comment by enchev** [comment]
Hey @carlosgjr,

We've fixed the problem with blank screens and we will upload new version soon (later today or tomorrow). Please regenerate your Radzen app when using the upcoming version.

**Comment by carlosgjr** [comment]
Thank you much

**Comment by carlosgjr** [comment]
I'm using version 1.1.5 and still see the same issue.

![radzen-issue-1](https://cloud.githubusercontent.com/assets/7093207/25948858/24a1869c-361b-11e7-987f-21a0ae3d8c60.png)

**Comment by akorchev** [comment]
@carlosgjr we are currently testing the 1.1.6 build which contains the fix. We will release it soon. Will post here

**Comment by enchev** [comment]
The latest (1.1.6) is live!
